import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../style/global.css";
import { ChallengesProvider } from "../contexts/ChallengesContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rest Technique",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ChallengesProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ChallengesProvider>
  );
}
